[build]
  publish = "."
  command = "echo 'build'"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/reddit"
  to = "/.netlify/functions/reddit"
  status = 200

[[redirects]]
  from = "/api/tiktok"
  to = "/.netlify/functions/tiktok"
  status = 200
