[build]
  publish = "."
  command = ""

[functions]
  directory = "."
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/reddit"
  to = "/.netlify/functions/reddit"
  status = 200

[[redirects]]
  from = "/api/tiktok"
  to = "/.netlify/functions/tiktok"
  status = 200
